// StackException.java - class for exceptions generated by the stack
// Author: Wim Bohm
// Course: CS165

public class StackException extends Exception {
	public StackException(){
		super("");
	}
	public StackException(String message){
		super(message);
	}
}
